window.SILS_DATA_EN = {
  lastUpdated: "2026-09-17",
  courses: [
    {
      id: "academic-writing-w315sp",
      title: "English Academic Writing, Level 3 W315SP",
      provider: "SILS",
      credits: 1,
      term: "Spring / Fall",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "multiple",
      experience: "Top-tier; the experience depends on how much you want to put into it. Even if you want to keep the workload light and avoid a lot of extra reading, you can still earn a decent grade.",
      fit: "Required; placement is based on your entrance English exam.",
      avoid: "",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CO12700152026210CO1270021&pLng=en",
      assessment: "",
      groupWork: "none",
      groupLabel: "N",
      tags: ["writing", "required", "english"]
    },
    {
      id: "comprehensive-japanese-4d",
      courseKey: "comprehensive-japanese-4",
      groupTitle: "Comprehensive Japanese 4",
      title: "Comprehensive Japanese 4",
      provider: "CJL",
      credits: 5,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 5,
      takenBy: "Chambers",
      teacher: "Classes are assigned randomly; each class has a different instructor.",
      experience: "Top-tier, but the workload is genuinely heavy and some assignments may feel pointless. If you read the texts seriously and actively participate in discussions and presentations, you can learn a lot. A useful rule of thumb: taking the level immediately below the one assigned by your Waseda placement test may make the class smoother and make a 5.0 GPA more realistic.",
      fit: "Students who are ready for the challenge.",
      avoid: "Students who want to take Japanese slowly and avoid a heavy Japanese-language workload.",
      assessment: "- Vocabulary quiz every Wednesday\n- Midterm exam\n- 5-minute presentation\n- Final exam\n- July 22: 1-minute speech",
      groupWork: "some",
      groupLabel: "Y",
      tags: ["japanese", "language", "cjl"]
    },
    {
      id: "manga-anime-japanese-5",
      title: "Learning Japanese through Manga and Anime 5",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 4,
      takenBy: "Chambers",
      teacher: "IMAI, Naomi",
      experience: "Top-tier and genuinely unusual, but not easy at all. The instructor does not simply lecture; students form interest-based groups and can visit real-life anime locations, draw manga, make a doujin magazine, or produce a fan-made music video for a virtual character. What matters most is a love of ACG culture plus imagination and strong execution. The final output is exhibited at a fair with one booth per group, and there is also a very detailed assessment table to complete entirely in Japanese.",
      fit: "Students who love ACG culture and bring imagination plus strong execution skills. Skills in drawing, video, music, or using AI tools to support design and media production are all a plus.",
      avoid: "Anyone expecting to watch anime together and coast to the credits without making anything.",
      assessment: "Instead of an exam, two submissions are required by the deadline: 1) reflection and evaluation (20%); 2) final product (10%). Both are graded for quality. The self-evaluation and final-task criteria include clarity, detail, authenticity, validity, consistency, completeness, usefulness, and creativity. Late or missing submissions cannot be graded.",
      groupWork: "heavy",
      groupLabel: "YYY",
      source: "https://drive.google.com/file/d/1x_ik2QYhxIrkT0pSvQ5Z59mn8BZOc7gx/view?usp=sharing",
      notes: "Check out our group's pilgrimage magazine.",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9204055005012026920405500592&pLng=en",
      tags: ["japanese", "acg", "creative", "project", "cjl"]
    },
    {
      id: "first-year-seminar-b-03",
      title: "First Year Seminar B 03",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "NAKAMURA, Chie",
      experience: "Top-tier; Professor Nakamura Chie is kind, approachable, and has excellent English. She holds a PhD from the University of Tokyo and is a scholar. The class focuses on linguistics: groups choose a research question and design a linguistics or psychology experiment. The main assessments are the midterm and final presentations.",
      fit: "Students interested in language who are willing to put in the time and have some teamwork experience. Because data analysis matters in the final presentation, basic statistics—such as t-tests, regression analysis, ANOVA, chi-square tests, and confidence levels—will help.",
      avoid: "Students looking for an easy credit or with no interest in linguistics or data analysis.",
      assessment: "Mainly the midterm and final presentations.",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GEB1000032026210GEB100021&pLng=en",
      tags: ["linguistics", "seminar", "data", "presentation"]
    },
    {
      id: "introduction-to-business-01",
      courseKey: "introduction-to-business",
      groupTitle: "Introduction to Business",
      title: "Introduction to Business 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 5,
      takenBy: "Chambers",
      teacher: "POKARIER, Christopher J",
      featured: true,
      verdict: "Top-tier",
      experience: "Top-tier. Many students say Christopher Pokarier is a hard pass because class can feel like casual conversation while the homework piles up: his own YouTube lectures, documentaries, and business cases. The exam may test tiny details, such as the true-or-false question built around a T-shirt he bought in Hawaii 20 years ago. I still think the class can connect ideas across fields if you take it seriously, especially through the final group project, which combines textbook knowledge with real-world needs.",
      fit: "Students interested in business competitions or projects who are willing to spend time on Poka's recommended YouTube material, rebuild their understanding of the course, and work with teammates on a business project.",
      avoid: "Students who want to build a systematic foundation in Business Management, Marketing, or Economics, or who do not want to spend significant time studying outside class.",
      assessment: "2 tests: 50%\nEngagement: 25%\n\nGroup project: 25%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20200012026210EB2020021&pLng=en",
      tags: ["business", "management", "marketing", "economics", "project"]
    },
    {
      id: "introduction-to-microeconomics-01",
      courseKey: "introduction-to-microeconomics",
      groupTitle: "Introduction to Microeconomics",
      title: "Introduction to Microeconomics 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "SHINO, Junnosuke",
      featured: true,
      verdict: "Top-tier",
      experience: "Top-tier; SHINO Junnosuke is very kind and patient when explaining difficult concepts, including game theory.",
      fit: "Students with little or no Economics or Calculus background who are interested in learning Economics.",
      avoid: "Students with extensive high-school Economics experience from A-levels, AP, or IB may find some explanations basic and long-winded. It is also possible that some material will not fit into class time and will appear on the exam as self-study.",
      assessment: "Two options:\n1. Midterm 30% + Final 30% + MindTap homework score 40%\n2. Midterm 50% + Final 50%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20500012026210EB2050021&pLng=en",
      tags: ["economics", "microeconomics", "beginner", "business"]
    },
    {
      id: "introduction-to-marketing-01",
      title: "Introduction to Marketing 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 4,
      takenBy: "Chambers",
      teacher: "MORIMOTO, Mariko",
      experience: "Top-tier, but you need to type constantly. The instructor does not provide slides; instead, there is a Word handout with many blanks that you need to fill in during class or risk missing material. You must buy the official Cengage textbook, or you will lose the points from the regular assignments.",
      fit: "Fast typists who can listen and type at the same time, and students willing to review after class and complete weekly Cengage assignments by their deadlines.",
      avoid: "Students who struggle with deadlines. Unlike SHINO's Microeconomics course, where the Cengage deadlines are concentrated near the end of term, this course gives you Cengage deadlines every week.",
      assessment: "Attendance/Participation: 10%\nOnline assignments: 30%\nFinal exam: 60%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20900012026210EB2090021&pLng=en",
      tags: ["marketing", "business", "cengage"]
    },
    {
      id: "english-plus-writing",
      title: "English Plus: Writing to Inform and Persuade 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "SNYDER, William Emmett",
      experience: "Average; the class is neither especially good nor especially bad. The professor is an American who studied in the former Soviet Union, grades generously, and can be a little soporific. This fall, there is a follow-up course, Writing to Entertain.",
      fit: "Students who enjoy writing and want to share work and peer-review each other's writing with experienced native speakers and Third Culture Kids.",
      avoid: "Students who want to build basic writing skills or whose Academic English Writing level is below 3. You may be working alongside native speakers and international-school students with five or more years of writing experience, so the class may not be a great fit if your English foundation is still developing or if you are only comfortable with IELTS-style argumentative essays.",
      assessment: "Three essays, all personal essays; academic citation is not required.\n\n- Process: explaining how to do something\n- Descriptive\n- Persuasive: 15,000 words, approximately five double-spaced pages\n\nWorkshop style: Professor Snyder hopes students will help one another and collaborate cohesively.\n\nSnyder: “I’m not gonna be policing your outside class.” About three hours per week should be enough for assignments.",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE16200012026210GE1620021&pLng=en",
      tags: ["writing", "english", "peer review"]
    },
    {
      id: "nihongo-1-2d",
      title: "Nihongo 1(2)D",
      provider: "CJL",
      credits: 2,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 1,
      takenBy: "Richard",
      teacher: "Classes are assigned randomly; each class has a different instructor.",
      experience: "Top-tier. This is a standard small-group Japanese class that is good for reinforcing the basics and practicing speaking. Class levels vary, and some students coast, but that also gives you room to improve if you want to. It is an on-demand online course, so you can take it from home while having breakfast.",
      fit: "Students with weak or shaky Japanese foundations, including students who want a low-workload way to earn the credits.",
      avoid: "Students who already have a strong foundation and want to push their Japanese further.",
      assessment: "Exams\nLesson tests: 30%, review sheet: 15%\nClass participation\nAttendance: 15%, class participation (worksheet): 15%\nOther\nPicture story: 10%, presentation: 10%, Q&A: 3%, self-evaluation: 2%",
      groupWork: "some",
      groupLabel: "Y",
      tags: ["japanese", "language", "online", "cjl"]
    },
    {
      id: "aural-oral-daily-conversation-2",
      title: "Aural-Oral: Practicing Daily Conversation and Usage 2",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 2,
      takenBy: "Richard",
      teacher: "UTSUNOMIYA, Youko",
      experience: "Top-tier. The workload is manageable, the class gives you useful Japanese speaking practice, and there are no obvious downsides.",
      fit: "Broadly the same as Nihongo 1(2)D: students who want manageable practice with everyday Japanese.",
      avoid: "Broadly the same as Nihongo 1(2)D: students looking for a much more advanced or intensive challenge.",
      assessment: "Class participation: 15%\nEvaluates active participation in pair/group work, in-class contributions, and presentations.\n\nHomework: 30%\nEvaluates weekly homework submission and content.\n\nTests: 45%\nConversation tests are administered in the 5th and 11th sessions.\n\nDrama-making and presentation: 10%\nEvaluates contribution to group work, presentation content, and performance.",
      groupWork: "heavy",
      groupLabel: "YYY",
      tags: ["japanese", "speaking", "conversation", "cjl"]
    },
    {
      id: "introductory-data-science-02",
      title: "Introductory Data Science 02",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 1,
      takenBy: "Richard",
      teacher: "SHINO, Junnosuke",
      experience: "Average; the difficulty and workload are both low. You can get close to full marks even if you coast and cram at the end, but be warned: SHINO Junnosuke has a very noticeable Japanese accent.",
      fit: "Required course; additional fit guidance is still pending.",
      avoid: "Required course; no separate skip guidance is currently available.",
      assessment: "Final examination + 6 quizzes",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE13100022026210GE1310021&pLng=en",
      tags: ["data science", "required", "beginner"]
    },
    {
      id: "first-year-seminar-b-35",
      title: "First Year Seminar B 35",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 4,
      takenBy: "Richard",
      teacher: "BERNARD, Rosemarie",
      experience: "Solid. The difficulty is a little high and the workload is somewhat large, but grading is generous. The workload is a 4 mainly because I took the class seriously; the real pressure comes from the volume and density of the reading. The professor is kind, knowledgeable, and widely liked.",
      fit: "Students who like Rosemarie's teaching style and are interested in Shinto.",
      avoid: "Students who do not want to read deeply.",
      assessment: "Exam 1: 25%\nExam 2: 25%\nFinal: 50%\nTotal: 100%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GEB1000352026210GEB100021&pLng=en",
      tags: ["seminar", "history", "religion", "reading"]
    },
    {
      id: "science-technology-society-01",
      title: "Science, Technology and Society 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Richard",
      teacher: "SIDOLI, Nathan Camillo",
      featured: true,
      verdict: "Top-tier",
      experience: "Top-tier. Professor Sidoli's lectures can be soporific, and electronic devices are not allowed in class. The main challenge is staying awake; once you follow the lecture, it is relatively easy to earn a high score on the exam.",
      fit: "Students interested in interdisciplinary study, especially Science and Technology Studies.",
      avoid: "Students who are not interested in the content, get sleepy easily, or rely on electronic devices during class.",
      assessment: "Midterm: 35%\nFinal: 35%\nActive participation: 30%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210LE20200012026210LE2020021&pLng=en",
      tags: ["science", "technology", "society", "sts"]
    },
    {
      id: "history-two-koreas-01",
      title: "APM: Introduction to Contemporary History of the Two Koreas 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Richard",
      teacher: "LEE, Bong Kyu",
      experience: "Top-tier. The professor is solid, the content is interesting, and you can either explore it deeply or take a lighter approach. The grading is reasonable.",
      fit: "Students interested in Korean or modern history, especially social and cultural history.",
      avoid: "Students expecting the course to focus in detail on North Korea.",
      assessment: "Final essay: 45%\nIndividual presentation or review paper: 40%\nActive participation: 15%",
      groupWork: "some",
      groupLabel: "Y (not mandatory)",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CU22800012026210CU2280021&pLng=en",
      tags: ["history", "korea", "apm"]
    },
    {
      id: "anthropology-chinese-studies-01",
      title: "APM: Anthropology and Chinese Studies in the 20th Century 01",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 2,
      takenBy: "Richard",
      teacher: "SHAN, Qi",
      experience: "Top-tier. The content is open to interpretation and includes plenty of controversial topics, but the discussion atmosphere is fairly constructive. The professor has a strong personality and clearly cares about teaching. A lot of Chinese is used in class, which may make you feel a little less homesick.",
      fit: "Students interested in modern Chinese society who have their own views and want to discuss them.",
      avoid: "Students who dislike debate or controversial topics.",
      assessment: "Class participation: 80%\nPapers: 20%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CM30500012026210CM3050021&pLng=en",
      tags: ["anthropology", "china", "apm", "discussion"]
    },
    {
      id: "media-popular-culture-01",
      title: "Media and Popular Culture 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 4,
      takenBy: "Richard",
      teacher: "NISHIMURA, Keiko",
      featured: true,
      verdict: "Top-tier",
      experience: "Top-tier. The course is interesting and has real depth, with examples connected to everyday life. Short presentations offer a lot of freedom, and the professor is friendly, enthusiastic, and excellent in class. The workload is heavy, but you can sometimes get by with AI-assisted reading.",
      fit: "Students interested in cultural studies, popular culture, media, or the humanities in general.",
      avoid: "Students who dislike abstract theory or treat popular culture and subculture as the same thing.",
      assessment: "Active participation: 15%\nQuizzes: 20%\nShow & Tell: 15%\nFilm responses: 20%\nMidterm exam: 15%\nFinal exam: 15%",
      groupWork: "heavy",
      groupLabel: "YYY",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CU34500012026210CU3450021&pLng=en",
      tags: ["media", "popular culture", "humanities", "presentation"]
    },
    {
      id: "philosophy-fys-b-61",
      title: "Introduction to Philosophy & First Year Seminar B 61",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 5,
      takenBy: "Richard",
      teacher: "NAGASAKA, Masumi",
      featured: true,
      verdict: "A hard pass",
      experience: "A hard pass. The professor is not a bad person, but the spoken English and accent can be difficult to follow. The rules are strict—for example, late homework gets an automatic zero—and the workload is brutal. You may be reading dozens of pages of Kant in the first week.",
      fit: "A philosophy nerd, a patient overachiever, or someone with a high tolerance for academic pain.",
      avoid: "Most normal people.",
      assessment: "Paper: 50%; participation, including regular homework: 50%",
      groupWork: "heavy",
      groupLabel: "Intro: N; FYS: YYY",
      syllabus: [
        "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210PR20100512026210PR2010021&pLng=en",
        "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GEB1000612026210GEB100021&pLng=en"
      ],
      tags: ["philosophy", "seminar", "reading", "heavy"]
    },
    {
      id: "psycholinguistics-51",
      title: "Introduction to Psycholinguistics 51",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 1,
      takenBy: "Richard",
      teacher: "LOVCEVIC, Irena",
      experience: "Solid, top-tier low-workload class. The class and homework are easy, but you still learn something. The professor is kind and does not like to see students get questions wrong, so being a little active in class and reviewing afterward can put an A+ within easy reach.",
      fit: "Students with some interest in the topic, even without prior knowledge, who want a low-workload way to earn a good grade.",
      avoid: "Students who want a serious, highly demanding challenge.",
      assessment: "Exam + paper + participation; percentages not listed",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CO20400512026210CO2040021&pLng=en",
      tags: ["psycholinguistics", "linguistics", "lighter"]
    },
    {
      id: "introduction-to-architecture",
      title: "Introduction to Architecture",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 5,
      takenBy: "Richard",
      teacher: "GOLANI SOLOMON, Erez",
      experience: "Average. The professor is an eccentric older German man with a faint Steve Jobs vibe: talented, but not always great at teaching, so you often have to figure things out yourself. The workload is intense. You must build models with both precision and creative ideas, but the effort does pay off in the grade.",
      fit: "Architecture students—the professor seems to assume everyone in the class studies architecture.",
      avoid: "Students without an architecture background.",
      assessment: "- Participation and contribution to the course: 15%\n- Assignments other than the final model, including work process, research initiatives, ideas, creativity, and craftsmanship in the assignments ‘Egg’, ‘Box’, and ‘Massing’/‘Analytical’: 45%\n- Final assignment/model, including work process, research initiatives, ideas, creativity, and craftsmanship in the ‘Final Model’: 40%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EX20600512026210EX2060021&pLng=en",
      tags: ["architecture", "model", "creative", "heavy"]
    },
    {
      id: "introduction-to-islamic-culture",
      title: "Introduction to Islamic Culture",
      provider: "SILS",
      credits: 2,
      term: "Fall",
      language: "English",
      workload: 2,
      takenBy: "Richard",
      teacher: "SAKURAI, Keiko",
      experience: "Solid. A very standard but exceptionally well-executed course: moderate workload, interesting content with some depth, and a friendly, experienced professor. It is hard to find a real downside.",
      fit: "Students interested in Islam.",
      avoid: "Students who are not interested in Islam or do not want to hear about the professor's fieldwork experiences.",
      assessment: "Midterm and final examinations: 90%\nParticipation: 10%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210PR20200512026210PR2020021&pLng=en",
      tags: ["islamic culture", "religion", "history", "lighter"]
    },
    {
      id: "reading-and-retelling-3-cindy",
      title: "Reading and Retelling 3",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 2,
      takenBy: "Cindy",
      sourceRow: 22,
      teacher: "WAKI, Keiko",
      experience: "Solid. Professor WAKI is warm and funny, and I strongly recommend her classes. Each session uses three readings: you read, retell them to a partner, and gradually reduce your notes from ten keywords to none. It noticeably improved my spoken Japanese and organized expression.",
      fit: "Students who want to improve Japanese speaking and express ideas in an organized way.",
      avoid: "Students who dislike working with unfamiliar classmates or speaking Japanese in front of others.",
      assessment: "Exam: 15%\nPapers: 15% — a text chosen by the student\nClass participation: 70%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9204033005012026920403300592&pLng=en",
      tags: ["japanese", "reading", "speaking", "cjl"]
    },
    {
      id: "vocabulary-building-5-6-cindy",
      title: "Vocabulary Building 5~6",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 5,
      takenBy: "Cindy",
      sourceRow: 23,
      teacher: "EYA, Yoko",
      experience: "A hard pass. I would avoid this instructor's classes. Before each week, students make very specific example sentences with two pages of vocabulary and particle combinations, but the work is not corrected and feedback is rare. Everyone is called on to share, cameras stay on, and the strict handwritten final exam gives zero for a wrong particle or a combination not taught in class. I ended with a C.",
      fit: "Students who like a heavy workload and strict instructors.",
      avoid: "In my view, this is a poor fit for non-native Japanese speakers generally.",
      assessment: "Final test: 70% — an in-person handwritten exam on the vocabulary usage taught in class.\nClass performance: 30% — submissions, attendance, lateness, and in-class presentations.",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9204A560010120269204A5600192&pLng=en",
      tags: ["japanese", "vocabulary", "cjl", "heavy"]
    },
    {
      id: "comprehensive-japanese-4-cindy",
      courseKey: "comprehensive-japanese-4",
      groupTitle: "Comprehensive Japanese 4",
      title: "Comprehensive Japanese 4",
      provider: "CJL",
      credits: 4,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 5,
      takenBy: "Cindy",
      sourceRow: 24,
      teacher: "OKUBO, Masako",
      experience: "Top-tier. Three in-person classes plus two days of online worksheets each week. The workload is fairly heavy, with a weekly grammar and vocabulary quiz, two presentations, and midterm and final exams.",
      fit: "Students who can track every deadline, are comfortable with a steady workload, and want more Japanese credits with a solid foundation.",
      avoid: "Students with weak Japanese foundations, trouble with verb conjugation, little tolerance for homework, or no interest in interacting with classmates.",
      assessment: "Exam: 30% — midterm 15%, final 15%\nClass participation: 20%\nOther: 50% — assignments 17%, written expression 12%, oral expression 16%, quizzes 5%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9200144999982026920014499992&pLng=en",
      tags: ["japanese", "language", "cjl"]
    },
    {
      id: "introduction-to-artificial-intelligence-cindy",
      title: "Introduction to Artificial Intelligence",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 1,
      takenBy: "Cindy",
      sourceRow: 25,
      teacher: "QI, Xin",
      experience: "Top-tier. A young Chinese professor whose spoken English is not always fluent but who sometimes tells funny examples. The class covers AI history, applications across fields, and useful terminology. Keep track of attendance and write the group-discussion answer sheet carefully because it likely counts toward participation. Midterm and final scores are not released and there is no feedback.",
      fit: "Students interested in AI who want a low-workload course.",
      avoid: "Students who fall asleep easily, expect hands-on AI practice, or already know AI and want an in-depth class.",
      assessment: "Papers: 80%\nClass participation: 20%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210MI20800012026210MI2080021&pLng=en",
      tags: ["artificial intelligence", "technology", "lighter"]
    },
    {
      id: "introduction-to-international-relations-cindy",
      title: "Introduction to International Relations",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 2,
      takenBy: "Cindy",
      sourceRow: 26,
      teacher: "Yamashita Hikaru",
      experience: "Solid. A kind and funny Japanese professor. Few students listen closely, so the course feels light. Write the two midterm and final reaction papers in response to the prompts and connect them to the class themes; good writing can earn an A+.",
      fit: "Students who prefer papers to exams and want a low-workload course.",
      avoid: "Students who dislike long papers or want to study current international relations and geopolitical issues in depth.",
      assessment: "Essays (reaction papers): 80%\nDiscussion participation: 20%",
      groupWork: "some",
      groupLabel: "Y",
      notes: "Choose Professor Yamashita Hikaru's section — there are no exams.",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210IR20100032026210IR2010021&pLng=en",
      tags: ["international relations", "politics", "lighter"]
    },
    {
      id: "introduction-to-business-cindy",
      courseKey: "introduction-to-business",
      groupTitle: "Introduction to Business",
      title: "Introduction to Business",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 5,
      takenBy: "Cindy",
      sourceRow: 27,
      teacher: "POKARIER, Christopher J",
      experience: "Top-tier. A 100+ student lecture that many people find stressful. Class itself covers very little, so expect to spend 2–3 hours each week watching YouTube videos; the midterm and final quizzes draw on very specific details from them. I learned a lot, and the group project was fun when the team members were responsible.",
      fit: "Students who enjoy YouTube learning, can remember details, are interested in business, and like group work and discussion.",
      avoid: "Students who do not want significant work after class, struggle to remember details, or do not want to collaborate on a project.",
      assessment: "Exam: 50% — two multiple-choice tests taken offline under exam conditions, currently planned for 20% in week 6 and 30% in week 13\nClass participation: 15% — engagement\nOther: 35% — group project",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20200012026210EB2020021&pLng=en",
      tags: ["business", "management", "project", "group work"]
    },
    {
      id: "introduction-to-microeconomics-cindy",
      courseKey: "introduction-to-microeconomics",
      groupTitle: "Introduction to Microeconomics",
      title: "Introduction to Microeconomics",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 2,
      takenBy: "Cindy",
      sourceRow: 28,
      teacher: "SHINO, Junnosuke",
      experience: "Solid. Professor Shino is very kind. There is a little Japanese accent, but the explanations are clear. He reviews the likely exam topics beforehand, and the questions are not difficult.",
      fit: "Students interested in Economics; even students with a weak foundation can follow it comfortably.",
      avoid: "Students who dislike exams or already have a strong foundation and want to study difficult material. Explanations can be slow and detailed, so experienced students may find it mostly review.",
      assessment: "The higher score from either calculation is used:\n1. Midterm 30% + Final 30% + MindTap homework score 40%\n2. Midterm 50% + Final 50%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20500012026210EB2050021&pLng=en",
      tags: ["economics", "microeconomics", "beginner"]
    },
    {
      id: "english-plus-speech-cindy",
      title: "English Plus: Speech and Public Speaking",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 3,
      takenBy: "Cindy",
      sourceRow: 29,
      teacher: "Yuko Aotani",
      experience: "Top-tier. Professor Yuko Aotani is kind, works as an NHK disaster announcer, and has excellent British pronunciation after studying in the UK. It is a small class of around 16 students, and almost every session includes a short speech—sometimes a memorable moment, sometimes a persuasive speech. Plan several hours before class to prepare and practice. The feedback and suggestions helped me improve noticeably over the term.",
      fit: "Students who want to improve English speaking and confidence, and students who want to meet strong English speakers.",
      avoid: "Students who dislike expressing opinions in public or cannot give a speech without reading from a script.",
      assessment: "Class contribution: 30%\nShort speech: 30%\nFinal presentation: 40%\nAttendance is extremely important. Missing 5 or more of 14 classes means you will not receive a grade.",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE16300012026210GE1630021&pLng=en",
      tags: ["english", "speaking", "presentation"]
    },
    {
      id: "introduction-to-statistics-a-cindy",
      title: "Introduction to Statistics A",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 1,
      takenBy: "Cindy",
      sourceRow: 30,
      teacher: "Ayako Suzuki",
      experience: "Top-tier. I felt confused through much of the semester, and students who did not study high school in China may need to put in extra work. In the final days I crammed, put every formula I needed on a cheat sheet, drilled Cengage review questions, and borrowed a scientific calculator. The exam turned out to be surprisingly easy.",
      fit: "Required course.",
      avoid: "Required course.",
      assessment: "The final course grade is based on the higher of two calculations:\n(1) Final examination 100%\n(2) Final examination 80% and quizzes/assignments 20%",
      groupWork: "none",
      groupLabel: "N",
      notes: "Strong recommendation for Professor Ayako Suzuki: patient, detailed explanations and very kind.",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE12200012026210GE1220021&pLng=en",
      tags: ["statistics", "required", "lighter"]
    }
  ],
  registration: [
    {
      id: "first-registration",
      dateLabel: "Sep 14, 9:00 AM\n– Sep 16, 4:00 PM (JST)",
      start: "2026-09-14T09:00:00+09:00",
      end: "2026-09-16T16:00:00+09:00",
      title: "First registration",
      action: "Submit your first-round course choices. Prepare both your preferred choices and backups before the window opens."
    },
    {
      id: "first-results",
      dateLabel: "Sep 24, 7:00 AM (JST)",
      start: "2026-09-24T07:00:00+09:00",
      end: "2026-09-24T09:00:00+09:00",
      title: "First results",
      action: "Check your results, any unfilled credits, and timetable conflicts."
    },
    {
      id: "second-registration",
      dateLabel: "Sep 24, 9:00 AM\n– Sep 25, 4:00 PM (JST)",
      start: "2026-09-24T09:00:00+09:00",
      end: "2026-09-25T16:00:00+09:00",
      title: "Second registration / Add-Drop",
      action: "Add or adjust courses based on your results. Check first whether a course can be dropped."
    },
    {
      id: "tutorial-payment",
      dateLabel: "Sep 25\n– Oct 1 (JST)",
      start: "2026-09-25T16:00:00+09:00",
      end: "2026-10-01T23:59:59+09:00",
      title: "Tutorial English payment",
      action: "Only applies to courses that require it. Follow the system instructions to complete payment."
    },
    {
      id: "second-results",
      dateLabel: "Sep 30, 7:00 AM (JST)",
      start: "2026-09-30T07:00:00+09:00",
      end: "2026-09-30T10:00:00+09:00",
      title: "Second results",
      action: "Check your status again and prepare for the third adjustment round."
    },
    {
      id: "classes-begin",
      dateLabel: "Oct 1 (JST)",
      start: "2026-10-01T00:00:00+09:00",
      end: "2026-10-01T23:59:59+09:00",
      title: "Classes begin",
      action: "Use your first week of class to test whether the workload and course are a good fit."
    },
    {
      id: "third-registration",
      dateLabel: "Oct 7, 9:00 AM\n– Oct 8, 4:00 PM (JST)",
      start: "2026-10-07T09:00:00+09:00",
      end: "2026-10-08T16:00:00+09:00",
      title: "Third registration / Add-Drop",
      action: "Complete the last major round of adjustments."
    },
    {
      id: "third-results",
      dateLabel: "Oct 13, 7:00 AM (JST)",
      start: "2026-10-13T07:00:00+09:00",
      end: "2026-10-13T10:00:00+09:00",
      title: "Third results",
      action: "Confirm your final timetable and any remaining action items."
    },
    {
      id: "course-payment",
      dateLabel: "Oct 14\n– Oct 19 (JST)",
      start: "2026-10-14T00:00:00+09:00",
      end: "2026-10-19T23:59:59+09:00",
      title: "Course payment",
      action: "Check which courses require payment and complete it by the deadline."
    },
    {
      id: "drop-only",
      dateLabel: "Oct 16\n9:00 AM–4:00 PM (JST)",
      start: "2026-10-16T09:00:00+09:00",
      end: "2026-10-16T16:00:00+09:00",
      title: "Drop-only window",
      action: "If you need to drop a course, confirm first that dropping is allowed and understand the consequences."
    }
  ],
  resources: [
    {
      name: "SILS Course Registration",
      type: "Official entry point",
      url: "https://www.waseda.jp/fire/sils/en/students/registration/",
      copy: "Download the course list, check registration rules, and see which courses are available in each round. Return here for the final check."
    },
    {
      name: "SILS Curriculum",
      type: "Official requirements",
      url: "https://www.waseda.jp/fire/sils/en/about/curriculum/",
      copy: "Check the 124-credit structure, SP1/SP2 requirements, required categories, and standard study plan."
    },
    {
      name: "MyWaseda",
      type: "Official action",
      url: "https://my.waseda.jp/login/login",
      copy: "Open Grade & Course Registration to submit your courses, then check the results yourself."
    },
    {
      name: "Waseda Syllabus Search",
      type: "Official course information",
      url: "https://www.wsl.waseda.jp/syllabus/JAA101.php?pLng=en",
      copy: "Confirm the instructor, course content, assessment breakdown, language, and latest class arrangements."
    },
    {
      name: "WasedaTime",
      type: "Third-party search",
      url: "https://wasedatime.com/courses/syllabus",
      copy: "Useful for quickly searching in English, comparing course information, and organizing your shortlist. It does not replace official information."
    },
    {
      name: "Wasedule",
      type: "Third-party management",
      url: "https://www.wasedule.com/downloads",
      copy: "Manage timetables, Moodle assignments, and the university calendar. The interface is mostly in Japanese, but it is useful for everyday deadlines."
    },
    {
      name: "Google Calendar",
      type: "Personal workflow",
      url: "https://calendar.google.com/",
      copy: "Keep registration deadlines, class schedules, and university events in one place. If the university offers a one-click add-to-calendar option, use it."
    }
  ]
};
