window.SILS_DATA = {
  lastUpdated: "2026-09-17",
  courses: [
    {
      id: "academic-writing-w315sp",
      title: "English Academic Writing, Level 3 W315SP",
      provider: "SILS",
      credits: 1,
      term: "Spring / Fall",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "multiple",
      experience: "顶级；体验感取决于你对自己的要求。如果不想太累，不去读大量课外的文献，也可以拿到不错的分数",
      fit: "必修；自动根据入学英语考分配",
      avoid: "",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CO12700152026210CO1270021&pLng=en",
      assessment: "",
      groupWork: "none",
      groupLabel: "N",
      tags: ["writing", "required", "english"]
    },
    {
      id: "comprehensive-japanese-4d",
      courseKey: "comprehensive-japanese-4",
      groupTitle: "Comprehensive Japanese 4",
      title: "Comprehensive Japanese 4",
      provider: "CJL",
      credits: 5,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 5,
      takenBy: "Chambers",
      teacher: "随机分配班级，每个班老师不一样。",
      experience: "人上人；课业量真的很大而且有些作业个人（包括身边大部分同学）感觉意义是不大的。但是如果认真读课文，actively engage 在课堂，包括小组讨论/发表的话，确实可以扎实学到东西。有一个general rule是可以选择比你做早大日语入门测测出来的水平低一个level的课体验会好一点，也更容易拿到5的GPA。",
      fit: "for those up for the challenges",
      avoid: "日语学习希望慢慢来，不希望有太多日语的课业压力的同学",
      assessment: "- Every Wed Vocab quiz\n- Mid-term Exam\n- 5min. Presentation\n-  Final Exam\n- 7.22: 1min. Speech",
      groupWork: "some",
      groupLabel: "Y",
      tags: ["japanese", "language", "cjl"]
    },
    {
      id: "manga-anime-japanese-5",
      title: "漫画・アニメから学ぶ日本語学習法5",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 4,
      takenBy: "Chambers",
      teacher: "IMAI, Naomi",
      experience: "人上人；很神奇的课但是一点都不轻松，老师完全不讲课而是让你们根据兴趣分组，去圣地巡礼，去画漫画，做同人杂志，做（同人）虚拟角色音乐MV都可以。最重要的是对ACG文化的热爱和想象力+执行力。最终的产出的部分出了会在一个fair上每个小组一个booth展出以外，还有一个非常复杂的assessment table（全部日语填写）",
      fit: "对ACG文化的热爱；有想象力+高执行力；会画画，视频创作，音乐制作，包括熟练使用AI工具进行辅助设计/生图/视频生成也都很加分。",
      avoid: "以为上课就是所有人一起看动漫，可以水学分的丝毫“不想动手“的二次元。",
      assessment: "試験の代わりに、以下の2点、期限内の提出を求めます。 1)振り返りと評価(20%) 2)成果物の提出(10%) いずれも「質」を求めます。 評価基準 自己評価 回答内容の質:わかりやすさ(具体的で詳細丁寧な、真正性・妥当性・一貫性) 評価基準 最終課題 質、妥当性、理解可能性(内容・詳細さ・わかりやすさ・完成度・有意味性・クリエイティビティ) ※クラスで合意をした提出の期限内までに提出してください。 ※未提出の場合は、評点できません。",
      groupWork: "heavy",
      groupLabel: "YYY",
      source: "https://drive.google.com/file/d/1x_ik2QYhxIrkT0pSvQ5Z59mn8BZOc7gx/view?usp=sharing",
      notes: "欢迎check我们的产出（圣地巡礼杂志）https://drive.google.com/file/d/1x_ik2QYhxIrkT0pSvQ5Z59mn8BZOc7gx/view?usp=sharing",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9204055005012026920405500592&pLng=en",
      tags: ["japanese", "acg", "creative", "project", "cjl"]
    },
    {
      id: "first-year-seminar-b-03",
      title: "First Year Seminar B 03",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "Nakamura Chie",
      experience: "顶级；中村智恵Nakamura Chie 老师人美心善而且英语很棒，东大的博士/学者。课是关于语言学的，大家分组之后，找课题然后设计语言学/心理学实验。最后评价方式主要就是期中和期末的两次presentation。",
      fit: "对语言序感兴趣，愿意花时间，有一定团队合作经验的同学；此外，因为最终的presentation里，数据分析也是很重要的一部分。基础的统计学知识会很有帮助（t-test/ regression analysis; ANOVA, Chi-Square test，CL level等）",
      avoid: "想轻松水学分；对语言学/数据分析毫无兴趣的同学",
      assessment: "主要就是期中和期末的两次presentation",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GEB1000032026210GEB100021&pLng=en",
      tags: ["linguistics", "seminar", "data", "presentation"]
    },
    {
      id: "introduction-to-business-01",
      courseKey: "introduction-to-business",
      groupTitle: "Introduction to Business",
      title: "Introduction to Business 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 5,
      takenBy: "Chambers",
      teacher: "Christopher Pokarier",
      featured: true,
      verdict: "人上人",
      experience: "人上人；很多人会评价Christopher Pokarier拉完了。原因很简单——上课侃大山，下课布置一堆Youtube视频（本人录制的网课+纪录片+商业案例），考试考查你“我在Module 4的视频里拿出来了一件我20年前在夏威夷买的T-shirt: 问你T/F”等。｜但是我觉得这门课，只要你认真是真的能够做到帮助你链接不同的领域的知识，通过最终的小组项目来结合textbook knowledge和real-world needs",
      fit: "对商赛，做项目感兴趣，愿意下课花大量时间利用Poka推荐的Ytb内容，重新学习课程内容，梳理知识体系，和队友一起完成商业projects的同学",
      avoid: "想系统性从零建构Business Management/Marketing/Economics的知识体系；不希望课外去花时间花精力大量学习内容的同学",
      assessment: "2 tests：50%\nEngagement：25%\n\nGroup Project：25%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20200012026210EB2020021&pLng=en",
      tags: ["business", "management", "marketing", "economics", "project"]
    },
    {
      id: "introduction-to-microeconomics-01",
      courseKey: "introduction-to-microeconomics",
      groupTitle: "Introduction to Microeconomics",
      title: "Introduction to Microeconomics 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "SHINO Junnosuke",
      featured: true,
      verdict: "顶级",
      experience: "顶级；SHINO Junnosuke 人很亚撒西！会很耐心的解释复杂的概念（比如Game Theory的部分）",
      fit: "对于经济学/Calculus零基础，但是有学习Econ兴趣的同学",
      avoid: "对于已经有丰富的在高中Alevel/AP/IB学习Econ的经验的同学来说可能有些地方的解释显得基础而冗长；另外值得一提的是会出现讲不完课，然后一部分内容就考自己课下补的情况。",
      assessment: "两个方案：1. Midterm 30% + Final 30%+ Homework@MindTap Score 40%\n2. Midterm 50% + Final 50%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20500012026210EB2050021&pLng=en",
      tags: ["economics", "microeconomics", "beginner", "business"]
    },
    {
      id: "introduction-to-marketing-01",
      title: "Introduction to Marketing 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 4,
      takenBy: "Chambers",
      teacher: "森本 真理子",
      experience: "人上人；老师不提供Slides但是提供一个挖了很多空的word笔记，需要你上课去疯狂敲字抄PPT，不然会错过东西。课本要求你必须购买Cengage正版不然你所有平时作业的分数就都没了；",
      fit: "打字快/擅长一边打字一边听讲，愿意下课花时间复习+每周完成Cengage上有ddl的作业的同学。",
      avoid: "不擅长管理DDL（因为Cengage每周都有DDL）对比SHINO的Microecnomics的所有Cengage 的DDL都是学期末，可以说非常苛刻了。",
      assessment: "Attendance/Participation10%\nOnline Assignments30%\nFinal Exam60%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20900012026210EB2090021&pLng=en",
      tags: ["marketing", "business", "cengage"]
    },
    {
      id: "english-plus-writing",
      title: "English Plus: Writing to Inform and Persuade 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Chambers",
      teacher: "Snyder",
      experience: "NPC; 感觉无功无过，教授是去前苏联留学过的美国老头，给分亚萨西，上课催眠。这个Fall学期开了续集Writing to Entertain",
      fit: "对写作有热情，希望有一个和有经验的母语者/Third Culture Kids一起交流，互相peer review彼此的writing的同学",
      avoid: "希望提升写作基本功，AE Writing没有到3的水平的同学；你在这里会和一堆写龄5年+的母语者/国际学校体现学生一起上课，个人感觉如果英语基础没有那么好或者很不擅长雅思议论文写作以外的写作的同学，来这边体验不会特别好",
      assessment: "Three essays, all personal essays(no academic citation required) \n\n- Process(how to do things)\n- Descriptive\n- Persuasive：15000 wds, approx. 5 pages, double-spaced margin\n\nWorkshop style: Prof. Snyder hopes we help each other and collaborate cohesively.\n\n- Snyder: “I’m not gonna be policing your outside class.”; 3h per week would be enough for assignments",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE16200012026210GE1620021&pLng=en",
      tags: ["writing", "english", "peer review"]
    },
    {
      id: "nihongo-1-2d",
      title: "Nihongo 1(2)D",
      provider: "CJL",
      credits: 2,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 1,
      takenBy: "Richard",
      teacher: "随机分配班级，每个班老师不一样。",
      experience: "人上人，标准日语小课，适合稳固基础+练习口语。同学水平参差不齐，有很多来划水的，但也可以借此机会努力提升自己的水平。On Demand网课，可以在家上顺便吃口早饭",
      fit: "日语水平弱且基础不牢固的同学，想划水拿学分的同学",
      avoid: "有基础且想提高日语水平的同学",
      assessment: " Exams\nLesson Tests 30%, Review Sheet 15%\nClass Participation\nAttendance 15%\r Class participation(Worksheet) 15%\nOthers\nPicture Story 10%, Presentation 10%, Q&A 3%, Self-evaluation 2%",
      groupWork: "some",
      groupLabel: "Y",
      tags: ["japanese", "language", "online", "cjl"]
    },
    {
      id: "aural-oral-daily-conversation-2",
      title: "Aural-Oral: Practicing Daily Conversation and Usage 2",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 2,
      takenBy: "Richard",
      teacher: "宇都宮 陽子",
      experience: "顶级。课业压力适中，有效练习日语口语，没有什么缺点。",
      fit: "基本同上",
      avoid: "基本同上",
      assessment: "平常点評価　１５％　\nEvaluates active participation in pair/group work, in-class contributions, and presentations.\n宿題　　３０％ \nEvaluates weekly homework submission and content.\nテスト　　４５％\nConversation tests will be administered in the 5th and 11th sessions.\nドラマ作り、発表　１０％　\nEvaluates contribution to group work, presentation content, and performance.\n",
      groupWork: "heavy",
      groupLabel: "YYY",
      tags: ["japanese", "speaking", "conversation", "cjl"]
    },
    {
      id: "introductory-data-science-02",
      title: "Introductory Data Science 02",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 1,
      takenBy: "Richard",
      teacher: "SHINO Junnosuke",
      experience: "NPC，低难度低任务量，划水一学期临时抱佛脚也能接近满分，但务必避雷SHINO, Junnosuke 篠　潤之介，日本口音集大成者",
      fit: "必修……",
      avoid: "必修……",
      assessment: "Final Examination + 6 Quizzes",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE13100022026210GE1310021&pLng=en",
      tags: ["data science", "required", "beginner"]
    },
    {
      id: "first-year-seminar-b-35",
      title: "First Year Seminar B 35",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 4,
      takenBy: "Richard",
      teacher: "BERNARD, Rosemarie",
      experience: "夯，难度略高，任务量稍大，但给分很宽容。workload给4主要在于我非常认真学，主要压力在于量大且信息密集的阅读。教授是慈祥老太太，人很好且很博学，好评如潮。",
      fit: "喜欢rosemarie教学方式的，对神道教感兴趣的",
      avoid: "不想深入阅读的",
      assessment: "Exam #1 25% Exam #2 25%, Final 50%= TOTAL 100%\r",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GEB1000352026210GEB100021&pLng=en",
      tags: ["seminar", "history", "religion", "reading"]
    },
    {
      id: "science-technology-society-01",
      title: "Science, Technology and Society 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Richard",
      teacher: "Sidoli",
      featured: true,
      verdict: "人上人",
      experience: "人上人，Sidoli教授讲课很催眠，且上课不允许使用电子设备。主要难点在于上课保持清醒，但一旦上课听懂了考试就能很轻松拿高分",
      fit: "对跨学科，尤其是Science and Technology Studies感兴趣的同学",
      avoid: "对内容无感/怕犯困/上课依赖电子产品的同学",
      assessment: "Midterm 35% \r Final 35%, Active Participation 30%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210LE20200012026210LE2020021&pLng=en",
      tags: ["science", "technology", "society", "sts"]
    },
    {
      id: "history-two-koreas-01",
      title: "APM: Introduction to Contemporary History of the Two Koreas 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 3,
      takenBy: "Richard",
      teacher: "LEE, Bong Kyu",
      experience: "顶级，教授不错，可以深入钻研也可以平平淡淡，内容有趣给分尚可。",
      fit: "对韩国历史/近现代史感兴趣的同学，专注于社会文化史的同学",
      avoid: "以为这门课会细讲朝鲜的同学",
      assessment: "Final Essay 45%  Individual Presentation or Review Paper 40%  Active Participation 15%",
      groupWork: "some",
      groupLabel: "Y (not mandatory)",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CU22800012026210CU2280021&pLng=en",
      tags: ["history", "korea", "apm"]
    },
    {
      id: "anthropology-chinese-studies-01",
      title: "APM: Anthropology and Chinese Studies in the 20th Century 01",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 2,
      takenBy: "Richard",
      teacher: "SHAN, Qi",
      experience: "人上人，课程内容见仁见智，有较多争议性话题但讨论氛围还可以，教授很有个性且对教学非常上心。课上大量使用中文，可以缓解思乡之情",
      fit: "对近现代中国社会感兴趣的同学，有自己的观点希望讨论的同学",
      avoid: "不喜欢争论和争议性话题的同学",
      assessment: "Class Participation 80%  Papers 20%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CM30500012026210CM3050021&pLng=en",
      tags: ["anthropology", "china", "apm", "discussion"]
    },
    {
      id: "media-popular-culture-01",
      title: "Media and Popular Culture 01",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 4,
      takenBy: "Richard",
      teacher: "NISHIMURA, Keiko",
      featured: true,
      verdict: "顶级",
      experience: "顶级，课程非常有趣且有深度，结合生活实例，小presentation自由度高。教授非常友好且热情，上课体验绝佳。课业量大但是可以划水（例如利用AI辅助阅读）",
      fit: "文化研究/流行文化/媒体/综合人文方向的同学",
      avoid: "不喜欢抽象理论的同学，把流行文化和亚文化等价的同学",
      assessment: "Active Participation 15%\nQuizzes 　　　20%\nShow & Tell 15%\nFilm Responses 20%\nMidterm Exam 15%\nFinal Exam 15%\n",
      groupWork: "heavy",
      groupLabel: "YYY",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CU34500012026210CU3450021&pLng=en",
      tags: ["media", "popular culture", "humanities", "presentation"]
    },
    {
      id: "philosophy-fys-b-61",
      title: "Introduction to Philosophy & First Year Seminar B 61",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 5,
      takenBy: "Richard",
      teacher: "NAGASAKA, Masumi",
      featured: true,
      verdict: "拉完了",
      experience: "拉完了。教授人不坏但英语口语较弱+口音严重，规则多且死板（例如过ddl无法补交直接0分），课业压力极大（第一周读几十页康德），压力巨大",
      fit: "抖M？哲学大佬？很有耐性的卷王？",
      avoid: "大部分正常人",
      assessment: "Both: 50% paper, 50% participation (include regular homework)",
      groupWork: "heavy",
      groupLabel: "Intro:N FYS:YYY",
      syllabus: [
        "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210PR20100512026210PR2010021&pLng=en",
        "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GEB1000612026210GEB100021&pLng=en"
      ],
      tags: ["philosophy", "seminar", "reading", "heavy"]
    },
    {
      id: "psycholinguistics-51",
      title: "Introduction to Psycholinguistics 51",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 1,
      takenBy: "Richard",
      teacher: "LOVCEVIC, Irena",
      experience: "夯，顶尖水课，上课课后都轻松但也有收获，教授心善看不得学生选错选项，上课稍微活跃一点+复习一下很轻松就A+。",
      fit: "对内容有些兴趣（即使0基础）的同学，想水课拿分的同学",
      avoid: "认真的卷王",
      assessment: "Exam + paper + participation, 比例未标明",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210CO20400512026210CO2040021&pLng=en",
      tags: ["psycholinguistics", "linguistics", "lighter"]
    },
    {
      id: "introduction-to-architecture",
      title: "Introduction to Architecture",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 5,
      takenBy: "Richard",
      teacher: "GOLANI SOLOMON, Erez",
      experience: "NPC，教授是古怪德国老先生，幻视乔布斯，有才华但是不是很会教学更多靠自己领悟。课业压力爆炸，需要动手做模型（高精度复刻还要有创意），但努力会有分数上的回报。",
      fit: "建筑学专业的学生（教授在心里默认了他的学生都是建筑学专业的）",
      avoid: "非建筑学专业的普通学生",
      assessment: "- Participation, contribution to the course: 15%\r\n- Assignments, other than the final model [work process, research initiatives, ideas, creativity and craftsmanship in the assignments ‘Egg’, ‘Box’, ‘Massing’/’Analytical’]: 45%\r\n- Final assignment/model [work process, research initiatives, ideas, creativity, and craftsmanship in the ‘Final Model’]: 40%\r",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EX20600512026210EX2060021&pLng=en",
      tags: ["architecture", "model", "creative", "heavy"]
    },
    {
      id: "introduction-to-islamic-culture",
      title: "Introduction to Islamic Culture",
      provider: "SILS",
      credits: 2,
      term: "Fall",
      language: "English",
      workload: 2,
      takenBy: "Richard",
      teacher: "SAKURAI, Keiko",
      experience: "夯。非常标准但也非常完美的课，课业压力中等，课程内容有趣+略有深度，教授友好且有丰富经验，挑不出缺点。",
      fit: "对伊斯兰有兴趣的学生",
      avoid: "对伊斯兰没兴趣的学生，不喜欢教授展示自己实地考察经历的学生",
      assessment: "Midterm and final examinations 90%, participation 10%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210PR20200512026210PR2020021&pLng=en",
      tags: ["islamic culture", "religion", "history", "lighter"]
    },
    {
      id: "reading-and-retelling-3-cindy",
      title: "Reading and Retelling 3",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 2,
      takenBy: "Cindy",
      sourceRow: 22,
      teacher: "WAKI, Keiko",
      experience: "夯。WAKI教授人超温柔幽默，强推她的所有课。每节课三篇文章，先读后跟同桌分别复述一遍，一开始可以在背面记录10个关键词，之后越减越少直到0个，口语表达能力提升了不少。",
      fit: "想要提高日语口语能力，有条理的表达能力的学生",
      avoid: "不喜欢和陌生人分组交流，害怕在他人面前展示口语能力的学生",
      assessment: "Exam:  15％\nPapers: 15％・自分で選(えら)んだ文章\nClass Participation: 70％",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9204033005012026920403300592&pLng=en",
      tags: ["japanese", "reading", "speaking", "cjl"]
    },
    {
      id: "vocabulary-building-5-6-cindy",
      title: "Vocabulary Building 5~6",
      provider: "CJL",
      credits: 1,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 5,
      takenBy: "Cindy",
      sourceRow: 23,
      teacher: "EYA, Yoko",
      experience: "拉完了，避雷，这个老师的所有课都避雷。每周上课前给两页词语和助词搭配，让自己造句，必须非常具体细节，但老师从来不改作业不给反馈。上课一个一个点名给全班分享，要求全程开摄像头+发言时开麦。老师很严，期末考试线下大卷子铅笔手写，只要助词错误或不是课堂讲得搭配就0分，最后美美拿到了一个C。",
      fit: "喜欢作业量大，严格老师的学生",
      avoid: "个人认为平等地不适合所有非日本人",
      assessment: "期末テスト：70％　教室の対面で、手書きで行います。授業で学んだ言葉の使い方が身についているかどうかを評価します。\n平常点：30％　提出物の状況、出欠・遅刻、授業中の発表などを総合して評価します。",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9204A560010120269204A5600192&pLng=en",
      tags: ["japanese", "vocabulary", "cjl", "heavy"]
    },
    {
      id: "comprehensive-japanese-4-cindy",
      courseKey: "comprehensive-japanese-4",
      groupTitle: "Comprehensive Japanese 4",
      title: "Comprehensive Japanese 4",
      provider: "CJL",
      credits: 4,
      term: "Spring / Fall",
      language: "Japanese",
      workload: 5,
      takenBy: "Cindy",
      sourceRow: 24,
      teacher: "待补充",
      experience: "人上人。每周3次线下课+2天的线上work sheet, 作业量偏多，每周一次语法+词汇quiz算入总成绩，一学期两次发表+期中期末考试。",
      fit: "喜欢一定任务量+对每项作业due记得很清楚的同学，想要多学分的日语基础不差的同学也推荐",
      avoid: "日语基础薄弱，动词变形掌握不到位，不想要过多作业，以及不喜欢跟同学交流的学生。",
      assessment: "Exam: 30％ 中間試験ちゅうかんしけん(15%)、期末試験きまつしけん(15%)\nClass Participation:20%\nOthers:50％ 課題かだい（17％）、文章ぶんしょう表現ひょうげん（12％）、口頭こうとう表現ひょうげん（16％）、クイズ（５％）",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=9200144999982026920014499992&pLng=en",
      tags: ["japanese", "language", "cjl"]
    },
    {
      id: "introduction-to-artificial-intelligence-cindy",
      title: "Introduction to Artificial Intelligence",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 1,
      takenBy: "Cindy",
      sourceRow: 25,
      teacher: "QI, Xin",
      experience: "人上人。年轻的中国男教授，英语口语不是那么流畅，但有时会讲一些搞笑的例子。学了AI的发展历史，不同领域的应用以及一些专业词汇等，课后记考勤，小组讨论的答案表要好好写，应该算入participation score。但期中期末考试不会发布成绩，也没有任何feedback。",
      fit: "对AI感兴趣，想要水课的同学。",
      avoid: "上课容易打瞌睡，以为会学到AI的实际应用和实操之类的学生。不适合有AI基础想要深入学习的学生。",
      assessment: "Papers: 80％\nClass Participation: 20%",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210MI20800012026210MI2080021&pLng=en",
      tags: ["artificial intelligence", "technology", "lighter"]
    },
    {
      id: "introduction-to-international-relations-cindy",
      title: "Introduction to International Relations",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 2,
      takenBy: "Cindy",
      sourceRow: 26,
      teacher: "山下光",
      experience: "夯。很慈祥幽默的日本教授，上课没有很多人认真听讲，比较水。只要期中期末两篇reaction paper按照题目结合讲过的主题写就可以，好好写很容易A+。",
      fit: "比起考试更喜欢写论文的学生，水课。",
      avoid: "不喜欢写长篇paper的学生/想学习当今国家关系以及局势的学生。",
      assessment: "80% Essays (reaction papers)\n20% Participation in the discussion.",
      groupWork: "some",
      groupLabel: "Y",
      notes: "记得选Yamashita Hikaru教授的国关！没有考试！！",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210IR20100032026210IR2010021&pLng=en",
      tags: ["international relations", "politics", "lighter"]
    },
    {
      id: "introduction-to-business-cindy",
      courseKey: "introduction-to-business",
      groupTitle: "Introduction to Business",
      title: "Introduction to Business",
      provider: "SILS",
      credits: 2,
      term: "Spring",
      language: "English",
      workload: 5,
      takenBy: "Cindy",
      sourceRow: 27,
      teacher: "POKARIER, Christopher J",
      experience: "人上人。很多人觉得压力大的一门课，100+人的大课。需要知道的是每周课堂上几乎不讲什么内容，课后需要每周花费2~3小时观看油管视频，期中期末的quiz也从中出题，而且题目非常细。对我来说学到了不少，分到负责的组员的话，group project也很有意思。",
      fit: "喜欢看油管视频，并能够记住里面提到过的细节，以及对商科感兴趣的学生。喜欢group work+discussion的学生。",
      avoid: "不想课后花费大量时间，记忆力差，不想和同学合作交流完成项目的学生。",
      assessment: "Exam: 50％  2 tests in Multiple Choice format, taken offline under exam conditions in the usual class time (currently planned for 20% in week 6, 30% in week 13).\nClass Participation: 15％  Engagement\nOthers: 35％ Group Project",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20200012026210EB2020021&pLng=en",
      tags: ["business", "management", "project", "group work"]
    },
    {
      id: "introduction-to-microeconomics-cindy",
      courseKey: "introduction-to-microeconomics",
      groupTitle: "Introduction to Microeconomics",
      title: "Introduction to Microeconomics",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 2,
      takenBy: "Cindy",
      sourceRow: 28,
      teacher: "SHINO Junnosuke",
      experience: "夯。Shino教授男非常優しい，虽然有一点点日式口音，但讲解很清楚明了。考试前回说明考点，题目也不难。",
      fit: "对经济感兴趣的学生，基础薄弱也可以轻松掌握。",
      avoid: "不喜欢考试，基础扎实，想要深入学习难点的学生。教授有时讲解过于细致或速度慢，对于有基础的同学相当于纯复习。",
      assessment: "取分数更高的一种算法： 1. Midterm 30% + Final 30% + Homework@MindTap Score 40%\n2. Midterm 50% + Final 50%",
      groupWork: "none",
      groupLabel: "N",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210EB20500012026210EB2050021&pLng=en",
      tags: ["economics", "microeconomics", "beginner"]
    },
    {
      id: "english-plus-speech-cindy",
      title: "English Plus: Speech and Public Speaking",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 3,
      takenBy: "Cindy",
      sourceRow: 29,
      teacher: "青谷優子",
      experience: "顶级。青谷优子教授人很好，是NHK的灾害播报员，以前在英国留过学所以英式发音很好。课堂是小课，一共16人左右。几乎每节课都要上台进行简短的演讲，有时候是一个难忘的瞬间，有时候persuasive speech。所以课前需要花费几个小时进行准备以及练习。老师会给反馈以及提升建议，一学期下来进步了不少！",
      fit: "想要提升英语口语和自信力的同学，希望认识更多优秀的英语口语表达者的同学一定要上",
      avoid: "不喜欢在公众面前表达自己的观点，演讲时完全不能脱稿的学生。",
      assessment: "Class contribution (30%), Short speech (30%), Final Presentation (40%)\nAttendance is extremely important. If you miss 5 or more classes out of 14, you will not receive a grade for the course",
      groupWork: "some",
      groupLabel: "Y",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE16300012026210GE1630021&pLng=en",
      tags: ["english", "speaking", "presentation"]
    },
    {
      id: "introduction-to-statistics-a-cindy",
      title: "Introduction to Statistics A",
      provider: "SILS",
      credits: 2,
      term: "Spring / Fall",
      language: "English",
      workload: 1,
      takenBy: "Cindy",
      sourceRow: 30,
      teacher: "鈴木彩子",
      experience: "顶级。一学期听的都很晕，高中没有在国内上的要下点功夫。最后几天极限复习，把需要用的公式全都写到cheat sheet上+狂刷cengage上的复习题，还借了朋友的scientific calculator, 结果考试出乎意料的简单。",
      fit: "必修",
      avoid: "必修",
      assessment: "The final course grade is based on the higher of two calculations:\n(1) Final examination 100%\n(2) Final examination 80% and Quizzes/Assignments 20%",
      groupWork: "none",
      groupLabel: "N",
      notes: "强推铃木彩子老师的课！！讲解耐心细致人很好",
      syllabus: "https://www.wsl.waseda.jp/syllabus/JAA104.php?pKey=210GE12200012026210GE1220021&pLng=en",
      tags: ["statistics", "required", "lighter"]
    }
  ],
  registration: [
    {
      id: "first-registration",
      dateLabel: "9 月 14 日 9:00\n至 9 月 16 日 16:00",
      start: "2026-09-14T09:00:00+09:00",
      end: "2026-09-16T16:00:00+09:00",
      title: "第一次注册",
      action: "提交第一版选课。提前准备候选和备选，不要等到最后一刻。"
    },
    {
      id: "first-results",
      dateLabel: "9 月 24 日 7:00",
      start: "2026-09-24T07:00:00+09:00",
      end: "2026-09-24T09:00:00+09:00",
      title: "第一次结果",
      action: "检查注册结果、空缺学分和时间冲突。"
    },
    {
      id: "second-registration",
      dateLabel: "9 月 24 日 9:00\n至 9 月 25 日 16:00",
      start: "2026-09-24T09:00:00+09:00",
      end: "2026-09-25T16:00:00+09:00",
      title: "第二次注册 / Add-Drop",
      action: "根据结果补课或调整。先确认课程是否允许退选。"
    },
    {
      id: "tutorial-payment",
      dateLabel: "9 月 25 日\n至 10 月 1 日",
      start: "2026-09-25T16:00:00+09:00",
      end: "2026-10-01T23:59:59+09:00",
      title: "Tutorial English 缴费",
      action: "仅适用于相关课程。按系统指引完成付款。"
    },
    {
      id: "second-results",
      dateLabel: "9 月 30 日 7:00",
      start: "2026-09-30T07:00:00+09:00",
      end: "2026-09-30T10:00:00+09:00",
      title: "第二次结果",
      action: "再次检查状态，并准备第三次调整。"
    },
    {
      id: "classes-begin",
      dateLabel: "10 月 1 日",
      start: "2026-10-01T00:00:00+09:00",
      end: "2026-10-01T23:59:59+09:00",
      title: "开课",
      action: "用第一周课堂体验验证 workload 与课程匹配度。"
    },
    {
      id: "third-registration",
      dateLabel: "10 月 7 日 9:00\n至 10 月 8 日 16:00",
      start: "2026-10-07T09:00:00+09:00",
      end: "2026-10-08T16:00:00+09:00",
      title: "第三次注册 / Add-Drop",
      action: "完成最后一轮主要调整。"
    },
    {
      id: "third-results",
      dateLabel: "10 月 13 日 7:00",
      start: "2026-10-13T07:00:00+09:00",
      end: "2026-10-13T10:00:00+09:00",
      title: "第三次结果",
      action: "确认最终课表和待处理事项。"
    },
    {
      id: "course-payment",
      dateLabel: "10 月 14 日\n至 10 月 19 日",
      start: "2026-10-14T00:00:00+09:00",
      end: "2026-10-19T23:59:59+09:00",
      title: "相关课程缴费",
      action: "检查需付费课程，并在期限内处理。"
    },
    {
      id: "drop-only",
      dateLabel: "10 月 16 日\n9:00 至 16:00",
      start: "2026-10-16T09:00:00+09:00",
      end: "2026-10-16T16:00:00+09:00",
      title: "Drop-only",
      action: "如需退课，先确认该课程是否允许退选及其后果。"
    }
  ],
  resources: [
    {
      name: "SILS Course Registration",
      type: "官方入口",
      url: "https://www.waseda.jp/fire/sils/en/students/registration/",
      copy: "下载课程列表、查看注册规则和每轮可选课程。所有最终判断先回到这里核对。"
    },
    {
      name: "SILS Curriculum",
      type: "官方要求",
      url: "https://www.waseda.jp/fire/sils/en/about/curriculum/",
      copy: "核对 124 学分、SP1 / SP2 结构、必修类别和标准修读计划。"
    },
    {
      name: "MyWaseda",
      type: "官方操作",
      url: "https://my.waseda.jp/login/login",
      copy: "进入 Grade & Course Registration，完成实际注册并自行检查结果。"
    },
    {
      name: "Waseda Syllabus Search",
      type: "官方课程信息",
      url: "https://www.wsl.waseda.jp/syllabus/JAA101.php?pLng=en",
      copy: "核对老师、授课内容、考核比例、语言和最新课堂安排。"
    },
    {
      name: "WasedaTime",
      type: "第三方搜索",
      url: "https://wasedatime.com/courses/syllabus",
      copy: "适合用英文快速搜索、比较课程资料和整理候选。不能替代官方信息。"
    },
    {
      name: "わせジュール",
      type: "第三方管理",
      url: "https://www.wasedule.com/downloads",
      copy: "管理时间表、Moodle 作业和学校日程。界面偏日语，但对日常 deadline 很实用。"
    },
    {
      name: "Google Calendar",
      type: "个人工作流",
      url: "https://calendar.google.com/",
      copy: "统一保存注册截止、课程安排和学校活动。遇到学校的一键添加入口可以直接使用。"
    }
  ]
};
